vile:
  ignore:
    - test/fixtures/**
    - test/**/*.js
    - .ackrc
    - bin
    - circle.yml
    - coverage
    - .git
    - node_modules
    - tags
    - .ctags
    - .editorconfig
    - .eslintignore
    - .eslintrc
    - .gitignore
    - .npmrc
    - .vile.yml
    - LICENSE

depcheck:
  config:
    ignore_dev_deps: false
    ignore_dirs:
      - src
      - typings
      - node_modules
      - coverage
      - haskell
      - ruby
      - tmp
    ignore_deps:
      - mocha
      - babel-cli
      - coffee-script
      - istanbul
      - release-it
      - npm-check-updates
      - typescript
      - wrench
      - pryjs
      - shelljs
      - "@forthright/*"

coverage:
  config:
    path: coverage/lcov.info

length:
  config:
    file: 100
    line: 80
  ignore: [
      "test/**/*.js",
      "test/*.js",
      "lib"
    ]

license:
  config:
    ignored:
      - cli-table
      - classifier
      - dox
      - esmangle-evaluator
      - growl
      - debug
      - commander
      - log-driver
      - microee
      - map-stream
      - event-stream
      - pjs
      - uri-templates
      - parsimmon
      - tweetnacl
      - split
      - tv4
      - forthright/vile-comment
      - forthright/vile-eslint
      - forthright/vile-length
      - forthright/vile-nsp
      - forthright/vile-stat
      - forthright/vile-tslint
      - forthright/vile-whitespace
      - forthright/vile-rubocop
      - forthright/vile-rubycritic
    disallowed: []
    allowed:
      - CC-BY-3.0
      - The MIT License
      - MIT
      - MIT AND CC-BY-3.0
      - (MIT AND JSON)
      - MPL
      - MPL-2.0
      - MPLv2.0
      - Public Domain
      - PSF
      - BSD
      - BSD-like
      - BSD-4-Clause
      - BSD-3-Clause
      - BSD-2-Clause
      - BSD-3-Clause AND MIT
      - BSD-2-Clause OR MIT
      - BSD-2-Clause OR WTFPL
      - BSD-2-Clause OR MIT OR Apache-2.0
      - Unlicense
      - Artistic-2.0
      - ISC
      - WTFPL
      - Apache
      - Apache2
      - Apache-2.0
      - Apache 2.0
      - Apache*
      - Apache License, Version 2.0
      - Apachev2
      - WTFPL
      - WTFPL OR MIT
      - GPL
