vile:
  ignore:
    - test/fixtures/**
    - test/**/*.js
    - .ackrc
    - bin
    - circle.yml
    - coverage
    - .git
    - node_modules
    - tags
    - .ctags
    - .editorconfig
    - .eslintignore
    - .eslintrc
    - .gitignore
    - .npmrc
    - .vile.yml
    - LICENSE

depcheck:
  config:
    ignore_dev_deps: false
    ignore_dirs:
      - src
      - typings
      - node_modules
      - coverage
      - haskell
      - ruby
      - tmp
    ignore_deps:
      - mocha
      - babel-cli
      - coffee-script
      - istanbul
      - release-it
      - npm-check-updates
      - typescript
      - wrench
      - pryjs
      - shelljs
      - "vile-*"
retire:
  config:
    node: true
    package: true
    js: false
