// Generated by CoffeeScript 1.9.3
var default_filter, filter, fs, init, minilog, quiet, verbose;

minilog = require('minilog');

fs = require('fs');

filter = new minilog.Filter();

default_filter = function() {
  filter.allow(/.*/, 'info');
  filter.allow(/.*/, 'warn');
  return filter.defaultResult = false;
};

quiet = function() {
  return filter.clear();
};

verbose = function(is_verbose) {
  if (is_verbose) {
    filter.clear();
    return filter.allow(/.*/, 'debug');
  } else {
    return default_filter();
  }
};

init = function() {
  if (process.env.LOGFILE) {
    minilog.pipe(filter).pipe(fs.createWriteStream(process.env.LOGFILE));
  } else {
    minilog.pipe(filter).pipe(minilog.backends.nodeConsole.formatNpm).pipe(minilog.backends.nodeConsole);
  }
  return default_filter();
};

module.exports = {
  create: minilog,
  verbose: verbose,
  quiet: quiet
};

init();
